# Generated by Django 6.0 on 2025-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mobil', models.CharField(max_length=100)),
                ('merek', models.CharField(max_length=50)),
                ('harga_sewa', models.IntegerField()),
                ('tgl_pengambilan', models.DateField()),
                ('tgl_pengembalian', models.DateField()),
            ],
        ),
    ]
